theme: jekyll-theme-minimal
title: AI &amp; NLP Lab
logo: /assets/img/logo-iu-red.png
description: The AI and Natural Language Processing Lab and Quantum AI Study Group
show_downloads: false
google_analytics: G-H2EHQ4SEQF
